name: Uloha 2 - Unit Test

on: [push]

jobs:
  test-python-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies (if any)
        run: |
          python -m pip install --upgrade pip

      - name: Run unit tests
        run: |
          python -m unittest discover -s . -p "test_*.py"

      - run: echo "🍏 This job's status is ${{ job.status }}."
